name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: 6.x
      
    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish ./BlazyorPreview.WASM/BlazyorPreview.WASM.csproj -c Release -o release
    
    # changes the base-tag in index.html from '/' to 'blazy' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to blazy
      run: sed -i 's/<base href="\/" \/>/<base href="\/blazy\/" \/>/g' release/wwwroot/index.html
    
    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
    
    # publish to github pages
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
